### ISSUE TITLE
Can a method be extracted to avoid duplication?

### ISSUE THREAD

**Issue by AlexKap23** [pothigai/RefactorSlotMachine#1]
https://github.com/pothigai/RefactorSlotMachine/blob/30644bf9d8b323a9c2add4291f6441718d70b995/Program.cs#L141-L200

I see that most of the content of those 2 methods is identical. Maybe a method can be created to avoid code duplication.

This method can take a parameter mode (to know if the calculation will be about rows or columns) and the slots.

The goal would be to end up with only one method for both of those.

**Comment by pothigai** [comment]
Resolved, replaced duplicate lines of code with a method for both checks.
